name: CI
on:
  push:
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install shards
        run: shards install
      - name: Run tests
        run: crystal spec --order=random -Dpreview_mt
      - name: Build docs
        run: crystal docs
      - name: Push to pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
      - name: Check formatting
        run: crystal tool format; git diff --exit-code
